import { useState, useEffect } from 'react'
import './App.css'

function App() {
   // State variables for dropdown selections
   const [selectedFaculty, setSelectedFaculty] = useState('');
   const [selectedCourse, setSelectedCourse] = useState('');
   const [selectedSkillType, setSelectedSkillType] = useState('');
   const [selectedSkill, setSelectedSkill] = useState('');
 
   // Original data (permanent data)
   const [data, setData] = useState([
    {
      id: 1,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Math Foundation',
      subskill: 'Number Theory',
      familiar: false,
    },
    {
      id: 2,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Math Foundation',
      subskill: 'Geometry',
      familiar: false,
    },
    {
      id: 3,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Problem Solving Skills',
      subskill: 'Computational Thinking',
      familiar: true,
    },
    {
      id: 4,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Problem Solving Skills',
      subskill: 'Algorithms',
      familiar: false,
    },
    {
      id: 5,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Variables, Contants, Data Types',
      familiar: false,
    },
    {
      id: 6,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Operators',
      familiar: false,
    },
    {
      id: 7,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Branching & Loops',
      familiar: true,
    },
    {
      id: 8,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Arrays',
      familiar: true,
    },
    {
      id: 9,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Functions',
      familiar: false,
    },
    {
      id: 10,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Strings',
      familiar: false,
    },
    {
      id: 11,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Variables, Data Types, Operators',
      familiar: false,
    },
    {
      id: 12,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Branching & Loops (Java)',
      familiar: false,
    },
    {
      id: 13,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Arrays (Java)',
      familiar: false,
    },
    {
      id: 14,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Data Abstraction',
      familiar: false,
    },
    {
      id: 15,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Inheritance',
      familiar: true,
    },
    {
      id: 16,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Polymorphism',
      familiar: true,
    },
    {
      id: 17,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Classes & Objects',
      familiar: false,
    },
    {
      id: 18,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Inheritance (Java)',
      familiar: true,
    },
    {
      id: 19,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Interfaces',
      familiar: false,
    },
    {
      id: 20,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Checked Exceptions',
      familiar: true,
    },
    {
      id: 21,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Unchecked Exceptions',
      familiar: false,
    },
    {
      id: 22,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Nested Exception',
      familiar: true,
    },
    {
      id: 23,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Custom Exceptions',
      familiar: false,
    },
    {
      id: 24,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Defining Packages',
      familiar: false,
    },
    {
      id: 25,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Importing classes, static members from Packages',
      familiar: true,
    },
    {
      id: 26,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Access Control',
      familiar: false,
    },
    {
      id: 27,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Standar Library',
      subskill: 'Java.lang package',
      familiar: false,
    },
    {
      id: 28,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Standar Library',
      subskill: 'java.util package',
      familiar: false,
    },
    {
      id: 29,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Input & Output Streams',
      familiar: false,
    },
    {
      id: 30,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Readers & Writers',
      familiar: false,
    },
    {
      id: 31,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Standard I/O',
      familiar: true,
    },
    {
      id: 32,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'ArrayList',
      familiar: false,
    },
    {
      id: 33,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'LinkedList',
      familiar: true,
    },
    {
      id: 34,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Maps',
      familiar: true,
    },
    {
      id: 35,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Sets',
      familiar: false,
    },
    {
      id: 36,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Algorithms (Java)',
      familiar: true,
    },
    {
      id: 37,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'ThreadCreation',
      familiar: true,
    },
    {
      id: 38,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'Mutual Exclusion',
      familiar: true,
    },
    {
      id: 39,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'Interthread Communication',
      familiar: false,
    },
    {
      id: 40,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'JSON Encoding & Decoding',
      subskill: 'Using JSON.Simple library',
      familiar: true,
    },
    {
      id: 41,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'Handling Excel Files',
      subskill: 'Using Apache POI',
      familiar: false,
    },
    {
      id: 42,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'Handling PDF Files',
      subskill: 'Using Apach PDFBox',
      familiar: true,
    },
    {
      id: 43,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Eclipse',
      subskill: 'Project Management',
      familiar: false,
    },
    {
      id: 44,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Eclipse',
      subskill: 'Source code control',
      familiar: true,
    },
    {
      id: 45,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Maven/Gradle',
      subskill: 'Building  Packages',
      familiar: true,
    },
    {
      id: 46,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Maven/Gradle',
      subskill: 'Importing Packages',
      familiar: true,
    },
    {
      id: 47,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'JUnit',
      subskill: 'Test cases',
      familiar: true,
    },
    {
      id: 48,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'JUnit',
      subskill: 'Test Fixture',
      familiar: true,
    },
    {
      id: 49,
      faculty: 'Salmon Joy',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'StarUML',
      subskill: 'Plotting Class Diagrams',
      familiar: false,
    },
    {
      id: 50,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Math Foundation',
      subskill: 'Number Theory',
      familiar: false,
    },
    {
      id: 51,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Math Foundation',
      subskill: 'Geometry',
      familiar: false,
    },
    {
      id: 52,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Problem Solving Skills',
      subskill: 'Computational Thinking',
      familiar: false,
    },
    {
      id: 53,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Problem Solving Skills',
      subskill: 'Algorithms',
      familiar: true,
    },
    {
      id: 54,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Variables, Contants, Data Types',
      familiar: false,
    },
    {
      id: 55,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Operators',
      familiar: true,
    },
    {
      id: 56,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Branching & Loops',
      familiar: true,
    },
    {
      id: 57,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Arrays',
      familiar: true,
    },
    {
      id: 58,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Functions',
      familiar: true,
    },
    {
      id: 59,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Strings',
      familiar: true,
    },
    {
      id: 60,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Variables, Data Types, Operators',
      familiar: true,
    },
    {
      id: 61,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Branching & Loops (Java)',
      familiar: true,
    },
    {
      id: 62,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Arrays (Java)',
      familiar: false,
    },
    {
      id: 63,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Data Abstraction',
      familiar: false,
    },
    {
      id: 64,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Inheritance',
      familiar: true,
    },
    {
      id: 65,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Polymorphism',
      familiar: true,
    },
    {
      id: 66,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Classes & Objects',
      familiar: true,
    },
    {
      id: 67,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Inheritance (Java)',
      familiar: false,
    },
    {
      id: 68,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Interfaces',
      familiar: false,
    },
    {
      id: 69,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Checked Exceptions',
      familiar: false,
    },
    {
      id: 70,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Unchecked Exceptions',
      familiar: true,
    },
    {
      id: 71,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Nested Exception',
      familiar: false,
    },
    {
      id: 72,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Custom Exceptions',
      familiar: false,
    },
    {
      id: 73,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Defining Packages',
      familiar: false,
    },
    {
      id: 74,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Importing classes, static members from Packages',
      familiar: true,
    },
    {
      id: 75,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Access Control',
      familiar: false,
    },
    {
      id: 76,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Standar Library',
      subskill: 'Java.lang package',
      familiar: true,
    },
    {
      id: 77,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Standar Library',
      subskill: 'java.util package',
      familiar: true,
    },
    {
      id: 78,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Input & Output Streams',
      familiar: true,
    },
    {
      id: 79,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Readers & Writers',
      familiar: false,
    },
    {
      id: 80,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Standard I/O',
      familiar: false,
    },
    {
      id: 81,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'ArrayList',
      familiar: false,
    },
    {
      id: 82,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'LinkedList',
      familiar: true,
    },
    {
      id: 83,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Maps',
      familiar: false,
    },
    {
      id: 84,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Sets',
      familiar: true,
    },
    {
      id: 85,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Algorithms (Java)',
      familiar: true,
    },
    {
      id: 86,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'ThreadCreation',
      familiar: false,
    },
    {
      id: 87,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'Mutual Exclusion',
      familiar: false,
    },
    {
      id: 88,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'Interthread Communication',
      familiar: true,
    },
    {
      id: 89,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'JSON Encoding & Decoding',
      subskill: 'Using JSON.Simple library',
      familiar: true,
    },
    {
      id: 90,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'Handling Excel Files',
      subskill: 'Using Apache POI',
      familiar: false,
    },
    {
      id: 91,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'Handling PDF Files',
      subskill: 'Using Apach PDFBox',
      familiar: false,
    },
    {
      id: 92,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Eclipse',
      subskill: 'Project Management',
      familiar: true,
    },
    {
      id: 93,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Eclipse',
      subskill: 'Source code control',
      familiar: true,
    },
    {
      id: 94,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Maven/Gradle',
      subskill: 'Building  Packages',
      familiar: true,
    },
    {
      id: 95,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Maven/Gradle',
      subskill: 'Importing Packages',
      familiar: false,
    },
    {
      id: 96,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'JUnit',
      subskill: 'Test cases',
      familiar: true,
    },
    {
      id: 97,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'JUnit',
      subskill: 'Test Fixture',
      familiar: true,
    },
    {
      id: 98,
      faculty: 'Rajesh Sola',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'StarUML',
      subskill: 'Plotting Class Diagrams',
      familiar: false,
    },
    {
      id: 99,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Math Foundation',
      subskill: 'Number Theory',
      familiar: false,
    },
    {
      id: 100,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Math Foundation',
      subskill: 'Geometry',
      familiar: true,
    },
    {
      id: 101,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Problem Solving Skills',
      subskill: 'Computational Thinking',
      familiar: false,
    },
    {
      id: 102,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Problem Solving Skills',
      subskill: 'Algorithms',
      familiar: false,
    },
    {
      id: 103,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Variables, Contants, Data Types',
      familiar: true,
    },
    {
      id: 104,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Operators',
      familiar: false,
    },
    {
      id: 105,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Branching & Loops',
      familiar: true,
    },
    {
      id: 106,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Arrays',
      familiar: true,
    },
    {
      id: 107,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Functions',
      familiar: true,
    },
    {
      id: 108,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Preskill',
      skill: 'Programming Essentials',
      subskill: 'Strings',
      familiar: true,
    },
    {
      id: 109,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Variables, Data Types, Operators',
      familiar: false,
    },
    {
      id: 110,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Branching & Loops (Java)',
      familiar: false,
    },
    {
      id: 111,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Basic Java Syntax',
      subskill: 'Arrays (Java)',
      familiar: true,
    },
    {
      id: 112,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Data Abstraction',
      familiar: false,
    },
    {
      id: 113,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Inheritance',
      familiar: false,
    },
    {
      id: 114,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'OOP Concepts',
      subskill: 'Polymorphism',
      familiar: true,
    },
    {
      id: 115,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Classes & Objects',
      familiar: true,
    },
    {
      id: 116,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Inheritance (Java)',
      familiar: false,
    },
    {
      id: 117,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Implementing OOP in Java',
      subskill: 'Interfaces',
      familiar: true,
    },
    {
      id: 118,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Checked Exceptions',
      familiar: false,
    },
    {
      id: 119,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Unchecked Exceptions',
      familiar: false,
    },
    {
      id: 120,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Nested Exception',
      familiar: true,
    },
    {
      id: 121,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Exception Handling',
      subskill: 'Custom Exceptions',
      familiar: false,
    },
    {
      id: 122,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Defining Packages',
      familiar: true,
    },
    {
      id: 123,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Importing classes, static members from Packages',
      familiar: false,
    },
    {
      id: 124,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Packages',
      subskill: 'Access Control',
      familiar: false,
    },
    {
      id: 125,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Standar Library',
      subskill: 'Java.lang package',
      familiar: false,
    },
    {
      id: 126,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Standar Library',
      subskill: 'java.util package',
      familiar: false,
    },
    {
      id: 127,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Input & Output Streams',
      familiar: false,
    },
    {
      id: 128,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Readers & Writers',
      familiar: true,
    },
    {
      id: 129,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'IO Streams & File Handling',
      subskill: 'Standard I/O',
      familiar: true,
    },
    {
      id: 130,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'ArrayList',
      familiar: true,
    },
    {
      id: 131,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'LinkedList',
      familiar: true,
    },
    {
      id: 132,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Maps',
      familiar: true,
    },
    {
      id: 133,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Sets',
      familiar: false,
    },
    {
      id: 134,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Colllections',
      subskill: 'Algorithms (Java)',
      familiar: true,
    },
    {
      id: 135,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'ThreadCreation',
      familiar: false,
    },
    {
      id: 136,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'Mutual Exclusion',
      familiar: false,
    },
    {
      id: 137,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tech/Core',
      skill: 'Threading & IPC in Java',
      subskill: 'Interthread Communication',
      familiar: false,
    },
    {
      id: 138,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'JSON Encoding & Decoding',
      subskill: 'Using JSON.Simple library',
      familiar: true,
    },
    {
      id: 139,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'Handling Excel Files',
      subskill: 'Using Apache POI',
      familiar: false,
    },
    {
      id: 140,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Domain/Applied Examples',
      skill: 'Handling PDF Files',
      subskill: 'Using Apach PDFBox',
      familiar: false,
    },
    {
      id: 141,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Eclipse',
      subskill: 'Project Management',
      familiar: true,
    },
    {
      id: 142,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Eclipse',
      subskill: 'Source code control',
      familiar: false,
    },
    {
      id: 143,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Maven/Gradle',
      subskill: 'Building  Packages',
      familiar: true,
    },
    {
      id: 144,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'Maven/Gradle',
      subskill: 'Importing Packages',
      familiar: false,
    },
    {
      id: 145,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'JUnit',
      subskill: 'Test cases',
      familiar: false,
    },
    {
      id: 146,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'JUnit',
      subskill: 'Test Fixture',
      familiar: false,
    },
    {
      id: 147,
      faculty: 'Mehul Shah',
      course: 'Object Oriented Programming with Java',
      skillType: 'Tool',
      skill: 'StarUML',
      subskill: 'Plotting Class Diagrams',
      familiar: true,
    },
    // Now proceeding to the next course: 'Computer Networks'
    // Faculty: 'Salmon Joy', 'Sivarajani S', etc.
  
    // Entries for 'Computer Networks' taught by 'Salmon Joy'
    {
      id: 148,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'Network Topologies',
      familiar: true,
    },
    {
      id: 149,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'OSI Layered Model',
      familiar: false,
    },
    {
      id: 150,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'TCP/IP Protocol Architecture',
      familiar: false,
    },
    {
      id: 151,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'Error Detection & Correction',
      familiar: false,
    },
    {
      id: 152,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Variables, Data Types',
      familiar: false,
    },
    {
      id: 153,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Operators',
      familiar: false,
    },
    {
      id: 154,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Branching & Loops (C programming)',
      familiar: false,
    },
    {
      id: 155,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Arrays',
      familiar: true,
    },
    {
      id: 156,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Pointers',
      familiar: true,
    },
    {
      id: 157,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Structures',
      familiar: true,
    },
    {
      id: 158,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Functions',
      familiar: false,
    },
    {
      id: 159,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Application Layer',
      subskill: 'HTTP Protocol',
      familiar: true,
    },
    {
      id: 160,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Application Layer',
      subskill: 'DNS',
      familiar: true,
    },
    // Note: There is an empty subskill in the CSV for Application Layer; we'll skip it.
    {
      id: 161,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: 'TCP Protocol',
      familiar: false,
    },
    {
      id: 162,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: 'UDP Protocol',
      familiar: true,
    },
    // Another empty subskill under Transprt Layer; we'll skip it.
    {
      id: 163,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'IP Protocol',
      familiar: true,
    },
    {
      id: 164,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'IP Routing',
      familiar: false,
    },
    {
      id: 165,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'Mobile IP',
      familiar: true,
    },
    {
      id: 166,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'MAC Protocol',
      familiar: true,
    },
    {
      id: 167,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'Wired Link Layer (Ethernet)',
      familiar: false,
    },
    {
      id: 168,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'Wireless Link Layer (WLAN)',
      familiar: true,
    },
    {
      id: 169,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'VLAN',
      familiar: true,
    },
    {
      id: 170,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Socket Programming',
      subskill: 'Socket APIs for TCP, UDP Communication',
      familiar: false,
    },
    {
      id: 171,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Socket Programming',
      subskill: 'IO Mutiplexing',
      familiar: true,
    },
    {
      id: 172,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'IOT',
      subskill: 'REST Client Example',
      familiar: false,
    },
    {
      id: 173,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'IOT',
      subskill: 'TCP, UDP for IOT Protocols',
      familiar: false,
    },
    {
      id: 174,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'Wireless Sensor Networks',
      subskill: 'Feasibility of Using TCP or UDP for WSNs',
      familiar: true,
    },
    {
      id: 175,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'Wireless Sensor Networks',
      subskill: 'MAC for IEEE 802.15.4',
      familiar: true,
    },
    {
      id: 176,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'Wireshark',
      subskill: 'Sniffing TCP, UDP Streams',
      familiar: true,
    },
    {
      id: 177,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'Wireshark',
      subskill: 'Sniffing HTTP Traffic',
      familiar: false,
    },
    {
      id: 178,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'Topology Design',
      familiar: true,
    },
    {
      id: 179,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'Configuring Routers & Switches',
      familiar: false,
    },
    {
      id: 180,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'VLAN Configuration',
      familiar: true,
    },
    {
      id: 181,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'SDN Setup',
      familiar: false,
    },
    {
      id: 182,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'Bandwidth & Latency Benchmarking',
      familiar: false,
    },
    {
      id: 183,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'Packet Loss Measurement',
      familiar: true,
    },
    {
      id: 184,
      faculty: 'Salmon Joy',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'TCP Window Scaling',
      familiar: false,
    },
    // Entries for 'Computer Networks' taught by 'Sivarajani S'
    {
      id: 185,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: 'TCP Protocol',
      familiar: true,
    },
    {
      id: 186,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: 'UDP Protocol',
      familiar: true,
    },
    {
      id: 187,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: '',
      familiar: true,
    },
    {
      id: 188,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'IP Protocol',
      familiar: false,
    },
    {
      id: 189,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'IP Routing',
      familiar: false,
    },
    {
      id: 190,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'Mobile IP',
      familiar: true,
    },
    {
      id: 191,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'MAC Protocol',
      familiar: false,
    },
    {
      id: 192,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'Wired Link Layer (Ethernet)',
      familiar: false,
    },
    {
      id: 193,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'Wireless Link Layer (WLAN)',
      familiar: false,
    },
    {
      id: 194,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'VLAN',
      familiar: true,
    },
    {
      id: 195,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Socket Programming',
      subskill: 'Socket APIs for TCP, UDP Communication',
      familiar: false,
    },
    {
      id: 196,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Socket Programming',
      subskill: 'IO Mutiplexing',
      familiar: true,
    },
    {
      id: 197,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'IOT',
      subskill: 'REST Client Example',
      familiar: true,
    },
    {
      id: 198,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'IOT',
      subskill: 'TCP, UDP for IOT Protocols',
      familiar: false,
    },
    {
      id: 199,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'Wireless Sensor Networks',
      subskill: 'Feasibility of Using TCP or UDP for WSNs',
      familiar: true,
    },
    {
      id: 200,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'Wireless Sensor Networks',
      subskill: 'MAC for IEEE 802.15.4',
      familiar: false,
    },
    {
      id: 201,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'Wireshark',
      subskill: 'Sniffing TCP, UDP Streams',
      familiar: true,
    },
    {
      id: 202,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'Wireshark',
      subskill: 'Sniffing HTTP Traffic',
      familiar: false,
    },
    {
      id: 203,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'Topology Design',
      familiar: true,
    },
    {
      id: 204,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'Configuring Routers & Switches',
      familiar: false,
    },
    {
      id: 205,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'VLAN Configuration',
      familiar: false,
    },
    {
      id: 206,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'SDN Setup',
      familiar: false,
    },
    {
      id: 207,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'Bandwidth & Latency Benchmarking',
      familiar: false,
    },
    {
      id: 208,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'Packet Loss Measurement',
      familiar: true,
    },
    {
      id: 209,
      faculty: 'Sivarajani S',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'TCP Window Scaling',
      familiar: true,
    },
    {
      id: 210,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'Network Topologies',
      familiar: true,
    },
    {
      id: 211,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'OSI Layered Model',
      familiar: false,
    },
    {
      id: 212,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'TCP/IP Protocol Architecture',
      familiar: true,
    },
    {
      id: 213,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'Data Communication & Network Basics',
      subskill: 'Error Detection & Correction',
      familiar: true,
    },
    {
      id: 214,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Variables, Data Types',
      familiar: true,
    },
    {
      id: 215,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Operators',
      familiar: true,
    },
    {
      id: 216,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Branching & Loops (C programming)',
      familiar: false,
    },
    {
      id: 217,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Arrays',
      familiar: false,
    },
    {
      id: 218,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Pointers',
      familiar: true,
    },
    {
      id: 219,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Structures',
      familiar: false,
    },
    {
      id: 220,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Preskill',
      skill: 'C Programming',
      subskill: 'Functions',
      familiar: true,
    },
    {
      id: 221,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Application Layer',
      subskill: 'HTTP Protocol',
      familiar: true,
    },
    {
      id: 222,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Application Layer',
      subskill: 'DNS',
      familiar: true,
    },
    {
      id: 223,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Application Layer',
      subskill: '',
      familiar: true,
    },
    {
      id: 224,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: 'TCP Protocol',
      familiar: false,
    },
    {
      id: 225,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: 'UDP Protocol',
      familiar: true,
    },
    {
      id: 226,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Transprt Layer',
      subskill: '',
      familiar: true,
    },
    {
      id: 227,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'IP Protocol',
      familiar: true,
    },
    {
      id: 228,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'IP Routing',
      familiar: false,
    },
    {
      id: 229,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Network Layer',
      subskill: 'Mobile IP',
      familiar: true,
    },
    {
      id: 230,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'MAC Protocol',
      familiar: true,
    },
    {
      id: 231,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'Wired Link Layer (Ethernet)',
      familiar: false,
    },
    {
      id: 232,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'Wireless Link Layer (WLAN)',
      familiar: false,
    },
    {
      id: 233,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Link Layer',
      subskill: 'VLAN',
      familiar: true,
    },
    {
      id: 234,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Socket Programming',
      subskill: 'Socket APIs for TCP, UDP Communication',
      familiar: false,
    },
    {
      id: 235,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tech/Core',
      skill: 'Socket Programming',
      subskill: 'IO Mutiplexing',
      familiar: true,
    },
    {
      id: 236,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'IOT',
      subskill: 'REST Client Example',
      familiar: false,
    },
    {
      id: 237,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'IOT',
      subskill: 'TCP, UDP for IOT Protocols',
      familiar: false,
    },
    {
      id: 238,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'Wireless Sensor Networks',
      subskill: 'Feasibility of Using TCP or UDP for WSNs',
      familiar: true,
    },
    {
      id: 239,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Domain/Applied Examples',
      skill: 'Wireless Sensor Networks',
      subskill: 'MAC for IEEE 802.15.4',
      familiar: false,
    },
    {
      id: 240,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'Wireshark',
      subskill: 'Sniffing TCP, UDP Streams',
      familiar: true,
    },
    {
      id: 241,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'Wireshark',
      subskill: 'Sniffing HTTP Traffic',
      familiar: false,
    },
    {
      id: 242,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'Topology Design',
      familiar: true,
    },
    {
      id: 243,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'Configuring Routers & Switches',
      familiar: false,
    },
    {
      id: 244,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'VLAN Configuration',
      familiar: false,
    },
    {
      id: 245,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'CISCO Packet Tracer',
      subskill: 'SDN Setup',
      familiar: false,
    },
    {
      id: 246,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'Bandwidth & Latency Benchmarking',
      familiar: false,
    },
    {
      id: 247,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'Packet Loss Measurement',
      familiar: true,
    },
    {
      id: 248,
      faculty: 'Mehul Shah',
      course: 'Computer Networks',
      skillType: 'Tool',
      skill: 'iperf',
      subskill: 'TCP Window Scaling',
      familiar: true,
    }
  ]
  );
 
   // Edited data (temporary changes)
   const [editedData, setEditedData] = useState([...data]);
 
   // Update editedData whenever data changes
   useEffect(() => {
     setEditedData([...data]);
   }, [data]);
 
   // Handler to toggle familiarity status in editedData
   const handleFamiliarityToggle = (id) => {
     const updatedEditedData = editedData.map((item) =>
       item.id === id ? { ...item, familiar: !item.familiar } : item
     );
     setEditedData(updatedEditedData);
   };
 
   // Handler for submit button to update data with editedData
   const handleSubmit = () => {
     setData(editedData);
     // Optionally, you can show a message or perform other actions
     alert('Changes saved successfully.');
   };
 
   // Extract unique options for dropdowns from the original data
   const faculties = [...new Set(data.map((item) => item.faculty))];
   const courses = [...new Set(data.map((item) => item.course))];
   const skillTypes = [...new Set(data.map((item) => item.skillType))];
   const skills = [...new Set(data.map((item) => item.skill))];
 
   // Filtered data based on dropdown selections, using editedData
   const filteredData = editedData.filter((item) => {
     return (
       (selectedFaculty === '' || item.faculty === selectedFaculty) &&
       (selectedCourse === '' || item.course === selectedCourse) &&
       (selectedSkillType === '' || item.skillType === selectedSkillType) &&
       (selectedSkill === '' || item.skill === selectedSkill)
     );
   });

  return (
    <>
         <div className="container mt-5">
      {/* Dropdowns Section */}
      <div className="card mb-4 shadow-sm">
        <div className="card-body">
          <form className="form-row">
            <div className="form-group col-md-3">
              <label htmlFor="facultySelect">Faculty</label>
              <select
                id="facultySelect"
                className="form-control"
                value={selectedFaculty}
                onChange={(e) => setSelectedFaculty(e.target.value)}
              >
                <option value="">All Faculties</option>
                {faculties.map((faculty, index) => (
                  <option key={index} value={faculty}>
                    {faculty}
                  </option>
                ))}
              </select>
            </div>
            <div className="form-group col-md-3">
              <label htmlFor="courseSelect">Course</label>
              <select
                id="courseSelect"
                className="form-control"
                value={selectedCourse}
                onChange={(e) => setSelectedCourse(e.target.value)}
              >
                <option value="">All Courses</option>
                {courses.map((course, index) => (
                  <option key={index} value={course}>
                    {course}
                  </option>
                ))}
              </select>
            </div>
            <div className="form-group col-md-3">
              <label htmlFor="skillTypeSelect">Skill Type</label>
              <select
                id="skillTypeSelect"
                className="form-control"
                value={selectedSkillType}
                onChange={(e) => setSelectedSkillType(e.target.value)}
              >
                <option value="">All Skill Types</option>
                {skillTypes.map((skillType, index) => (
                  <option key={index} value={skillType}>
                    {skillType}
                  </option>
                ))}
              </select>
            </div>
            <div className="form-group col-md-3">
              <label htmlFor="skillSelect">Skill</label>
              <select
                id="skillSelect"
                className="form-control"
                value={selectedSkill}
                onChange={(e) => setSelectedSkill(e.target.value)}
              >
                <option value="">All Skills</option>
                {skills.map((skill, index) => (
                  <option key={index} value={skill}>
                    {skill}
                  </option>
                ))}
              </select>
            </div>
          </form>
        </div>
      </div>

      {/* Table Section */}
      <div className="card shadow-sm">
        <div className="card-header bg-primary text-white">
          <h4 className="mb-0">Skill Matrix</h4>
        </div>
        <div className="card-body p-0">
          <div className="table-responsive">
            <table className="table table-bordered table-hover mb-0">
              <thead className="thead-light">
                <tr>
                  <th>Faculty</th>
                  <th>Course</th>
                  <th>Skill Type</th>
                  <th>Skill</th>
                  <th>Subskill</th>
                  <th>Familiar</th>
                </tr>
              </thead>
              <tbody>
                {filteredData.length > 0 ? (
                  filteredData.map((row) => (
                    <tr key={row.id}>
                      <td>{row.faculty}</td>
                      <td>{row.course}</td>
                      <td>{row.skillType}</td>
                      <td>{row.skill}</td>
                      <td>{row.subskill}</td>
                      <td>
                        <div className="custom-control custom-switch">
                          <input
                            type="checkbox"
                            className="custom-control-input"
                            id={`familiarSwitch${row.id}`}
                            checked={row.familiar}
                            onChange={() => handleFamiliarityToggle(row.id)}
                          />
                          <label
                            className="custom-control-label"
                            htmlFor={`familiarSwitch${row.id}`}
                          >
                            {row.familiar ? 'Yes' : 'No'}
                          </label>
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="6" className="text-center">
                      No data available.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
        <div className="card-footer text-right">
          <button className="btn btn-primary" onClick={handleSubmit}>
            Submit
          </button>
        </div>
      </div>
    </div>
    </>
  )
}

export default App
